//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHang
    {
        public int DonHangID { get; set; }
        public int MTID { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual MT MT { get; set; }
    }
}
