//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.MTs = new HashSet<MT>();
        }
    
        public int DanhMucID { get; set; }
        public string TenDanhMuc { get; set; }
    
        public virtual ICollection<MT> MTs { get; set; }
    }
}
