//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int DanhGiaID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> MTID { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string NoiDungDanhGia { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual MT MT { get; set; }
    }
}
