//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public int DonHangID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TrangThaiDonHang { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public string DiaChiGiaoHang { get; set; }
    
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
