//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.DonHangs = new HashSet<DonHang>();
            this.LIENHEs = new HashSet<LIENHE>();
        }
    
        public int KhachHangID { get; set; }
        public string TenKhachHang { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
    
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<LIENHE> LIENHEs { get; set; }
    }
}
