//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT
    {
        public MT()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int MTID { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> DanhMucID { get; set; }
        public Nullable<int> SoLuongKho { get; set; }
        public string ThuongHieu { get; set; }
        public string ViXuLy { get; set; }
        public string RAM { get; set; }
        public string LuuTru { get; set; }
        public string KichThuocManHinh { get; set; }
        public string MauSac { get; set; }
        public string DungLuongPin { get; set; }
        public string DuongDan { get; set; }
    
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
